# Botfront para staging


version: "3.8"

networks:
  private:
  ingress:
    external: true
    name: ${INGRESS_NET}
    
 
volumes:
  rasa_data:
  rasa_actions_data:
  db_data:

services:

      
  botfront:
    image: ${BF_IMAGE}
    deploy:
      placement:
        constraints:
          - node.labels.${NODE_LABEL} == 1 
      labels:
        - traefik.enable=true
        - traefik.docker.network=${INGRESS_NET}
        - traefik.constraint-label=${INGRESS_NET}
        - traefik.http.routers.${NAME}-http.rule=Host(`${DOMAIN}`)
        - traefik.http.routers.${NAME}-http.entrypoints=http
        - traefik.http.routers.${NAME}-http.middlewares=https-redirect
        - traefik.http.routers.${NAME}-https.rule=Host(`${DOMAIN}`)
        - traefik.http.routers.${NAME}-https.entrypoints=https
        - traefik.http.routers.${NAME}-https.tls=true
        - traefik.http.routers.${NAME}-https.tls.certresolver=le
        - traefik.http.services.${NAME}.loadbalancer.server.port=3000
    networks:
      - private
      - ingress
    volumes:
      - rasa_data:/app/models:ro
    environment:
      - PORT=3000
      - ROOT_URL=https://botfront.${NAME}.saia.ar
      - AUGMENTATION_FACTOR=50
      - MONGO_URL=mongodb://mongo:27017/bf
      
  actions:
    image: ${ACTIONS_IMAGE}
    deploy:
      placement:
        constraints:
          - node.labels.botfront.${NODE_LABEL} == 1 
    networks:
      - private
    volumes:
      - rasa_actions_data:/app/actions
    command:
      - start
      - --debug
      - --actions
      - actions
    environment:
      - BF_PROJECT_ID=${BF_PROJECT_ID}
      
  duckling:
    image: ${DUCKLING_IMAGE}
    deploy:
      placement:
        constraints:
          - node.labels.botfront.${NODE_LABEL} == 1 
    networks:
      - private
     
  mongo:
    image: ${MONGO_IMAGE}
    deploy:
      resources:
        limits:
          cpus: ${MONGO_CPU_LIMIT}
          memory: ${MONGO_MEMORY_LIMIT}
        reservations:
          cpus: ${MONGO_CPU_RESERVATION}
          memory: ${MONGO_MEMORY_RESERVATION}
      placement:
        constraints:
          - node.labels.botfront.${NODE_LABEL} == 1 
    networks:
      - private
    volumes:
      - db_data:/data/db

  rasa:
    image: ${RASA_IMAGE}
    deploy:
      resources:
        limits:
          cpus: ${RASA_CPU_LIMIT}
          memory: ${RASA_MEMORY_LIMIT}
        reservations:
          cpus: ${RASA_CPU_RESERVATION}
          memory: ${RASA_MEMORY_RESERVATION}
      placement:
        constraints:
          - node.labels.botfront.${NODE_LABEL} == 1 
      labels:
        - traefik.enable=true
        - traefik.docker.network=${INGRESS_NET}
        - traefik.constraint-label=${INGRESS_NET}
        - traefik.http.routers.rasa_${NAME}-http.rule=Host(`${SOCKET_URL}`)
        - traefik.http.routers.rasa_${NAME}-http.entrypoints=http
        - traefik.http.routers.rasa_${NAME}-http.middlewares=https-redirect
        - traefik.http.routers.rasa_${NAME}-https.rule=Host(`${SOCKET_URL}`)
        - traefik.http.routers.rasa_${NAME}-https.entrypoints=https
        - traefik.http.routers.rasa_${NAME}-https.tls=true
        - traefik.http.routers.rasa_${NAME}-https.tls.certresolver=le
        - traefik.http.services.rasa_${NAME}.loadbalancer.server.port=5005
    networks:
      - private
      - ingress
    volumes:
      - rasa_data:/app/models
    environment:
      - BF_PROJECT_ID=${BF_PROJECT_ID}
      - BF_URL=http://botfront:3000/graphql
      - AUGMENTATION_FACTOR=50
      - MONGO_URL=mongodb://mongo:27017/bf